# Generated by Django 2.2.7 on 2019-11-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50, verbose_name='TITLE')),
                ('Content', models.CharField(max_length=50, verbose_name='CONTENT')),
            ],
        ),
    ]
