# Generated by Django 2.2.7 on 2019-11-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191124_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='birthCity',
            field=models.CharField(max_length=50, null=True, verbose_name='birthCity'),
        ),
        migrations.AddField(
            model_name='blog',
            name='birthYear',
            field=models.IntegerField(null=True, verbose_name='birthYear'),
        ),
        migrations.AddField(
            model_name='blog',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='blog',
            name='surname',
            field=models.CharField(max_length=50, null=True, verbose_name='surname'),
        ),
    ]
