# Generated by Django 2.2.7 on 2019-11-27 02:16

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191124_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='lnglat',
            field=models.CharField(blank=True, help_text='경도, 위도 포맷으로 입력', max_length=50, null=True, validators=[blog.models.lnglat_validator]),
        ),
    ]
