# Generated by Django 2.2.7 on 2019-11-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_lnglat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Content',
            field=models.CharField(max_length=50, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
