# Generated by Django 2.2.7 on 2019-11-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191128_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Content',
            field=models.CharField(max_length=50, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Title',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='createDate',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='createDate'),
        ),
    ]
