# Generated by Django 2.2.7 on 2019-11-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20191128_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='level',
            field=models.IntegerField(null=True, verbose_name='level'),
        ),
    ]
