# Generated by Django 2.2.7 on 2019-11-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20191128_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='level2',
            field=models.IntegerField(null=True, verbose_name='level2'),
        ),
    ]
