# Generated by Django 2.2.7 on 2019-11-28 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_menu_level2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='level2',
        ),
    ]
